fix: remove docusaurus 2 site from workspace (#114)
Summary:
Received report that docusaurus 2 site in fbt was not working.

```shell
>yarn build
yarn run v1.19.1
$ docusaurus build
Creating an optimized production build...

✖ Client
  Compiled with some errors in 1.03s

● Server █████████████████████████ building (12%) 23/26 modules 3 active
 ../node_modules/react-loadable/lib/index.js

../node_modules/docusaurus/core/lib/client/clientEntry.js
Error: [BABEL] /Users/jwatson/workspace/fbt/node_modules/docusaurus/core/lib/client/clientEntry.js: Invalid Option: corejs is not a valid top-level option.
        Maybe you meant to use 'targets'? (While processing: "/Users/jwatson/workspace/fbt/node_modules/babel/preset-env/lib/index.js")
    at Array.reduce (<anonymous>)

✖ Client
  Compiled with some errors in 1.03s

● Server █████████████████████████ building (34%) 206/207 modules 1 active
 ../node_modules/react-toggle/dist/component/x.js
```

It's because how yarn hoist modules and resolve dependencies. There are various conflicting versions of 'babel/core', and etc.

For example: Docusaurus 2 depends on lot of latest version of babel https://github.com/facebook/docusaurus/blob/cc2201e997c660f8a334e5d5ada27994d04697f0/packages/docusaurus/package.json#L35-L40

while the fbt repo **pin the babel/core dependencies** on certain exact older version.
https://github.com/facebookincubator/fbt/blob/master/package.json

Yarn workspace isn't perfect so it resolves the wrong and older deps :O

There are two solutions for this
1. Remove website from part of yarn workspace (what this PR do). So its independent and you'll have to `cd website` and `yarn` there
2. Stop pinning to old dependencies and let website still be part of same workspace.. However, I'm not fully aware of all fbt internal as such why deps are pinned  so I didn't do this solution.
Pull Request resolved: https://github.com/facebookincubator/fbt/pull/114

Test Plan:
<img width="630" alt="website-yarnstart" src="https://user-images.githubusercontent.com/17883920/70045984-afdfb300-15f7-11ea-8d65-af61febcea37.PNG">
<img width="549" alt="yarnbuild" src="https://user-images.githubusercontent.com/17883920/70045985-afdfb300-15f7-11ea-8fc0-1192c69ba88e.PNG">
<img width="956" alt="2" src="https://user-images.githubusercontent.com/17883920/70045992-b1a97680-15f7-11ea-806f-2cc2d8dfc47d.PNG">

Differential Revision: D18782438

Pulled By: jrwats

fbshipit-source-id: a26f60545230d9dce23af1bb0cb4249b4c9ec249